### ISSUE TITLE
tutorial?

### ISSUE THREAD

**Issue by deadbaed** [Shaneee92/HighSierra_Minimal#1]
hi, is there some tutorial on how to compile it and install it and put it in clover?

i know how to compile and install the linux kernel, i just never did that with xnu, since i know apple does stuff differently...

thanks for the hard work on amd-osx!

**Comment by Shaneee** [comment]
Xcode 9.2 with matching CLI is needed for 10.13.3. Then use this to build the dependancies. https://gist.github.com/afrighetto/e47b990f52586b4797297e7548e6352c

CD to the folder it's located and run this in Terminal. `MACOS_VERSION=10.13.3 ./build-xnu.sh`

You don't put it in Clover. It replaces the vanilla kernel then you build the prelinkedkernel to match it.
